/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "finger.h"

bool_t
xdr_finger_out (XDR *xdrs, finger_out *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->message, 1024,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}
